### PR TITLE
created docsify setup for the project

### PR DESCRIPTION
**Pull request by ReneVolution**
Hey there,

I have created a simple UI, based on docsify for the README contents. Do try it out, you'd can install docsify via `npm install -g docsify` and run `docsify serve ./docs` from within the repo.

What do you think?

### CODE REVIEW

**Comment by greybax** [comment]
This looks pretty good! 😄 Just one more thing. May be do `npm init` with devDependencies 'docsify' for this repo and add npm script like `serve` for `doscify serve ./docs` instead of installing docsify globally?

**Comment by ReneVolution** [comment]
There you go :) ... please double check the values in package.json, as not everything was obvious.

**Comment by greybax** [comment]
Thank you @ReneVolution! I'm gonna merge these changes in master branch now. Please let me know if you have another changes here.

**Comment by ReneVolution** [comment]
Sure Thing. I am glad I could help. Will pick this up again for sure 😸

**Pull request merged**
